# Generated by Django 4.1.2 on 2022-10-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_fname', models.CharField(max_length=100)),
                ('client_lname', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=100)),
                ('client_dobdate', models.DateField()),
                ('client_email', models.EmailField(max_length=254)),
                ('client_password', models.CharField(max_length=100)),
                ('client_contact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
