# Generated by Django 4.1.2 on 2022-10-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_fname',
            new_name='client_First_name',
        ),
    ]
