# Generated by Django 4.1.2 on 2022-11-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_rename_client_fname_client_client_first_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client',
            new_name='Customer',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
