# Generated by Django 4.1.2 on 2022-11-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_rename_client_customer_alter_customer_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='client_First_name',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='client_contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='client_dobdate',
            new_name='DOBdate',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='client_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='client_address',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='client_lname',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='client_password',
            new_name='password',
        ),
    ]
