# Generated by Django 4.1.2 on 2022-11-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_rename_client_first_name_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Topic',
            },
        ),
    ]
