# Generated by Django 4.1.2 on 2022-11-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_topic'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table=None,
        ),
    ]
