# Generated by Django 4.1.2 on 2022-11-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_alter_service_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Servic',
        ),
    ]
