# Generated by Django 4.1.2 on 2022-11-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_custome_delete_customer_alter_service_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('DOBdate', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.DeleteModel(
            name='Custome',
        ),
    ]
