# Generated by Django 4.1.2 on 2022-11-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_customer_delete_custome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='DOBdate',
            new_name='DOB',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
