# Generated by Django 4.1.2 on 2022-11-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_rename_dobdate_customer_dob_alter_customer_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ourservice',
        ),
    ]
