# Generated by Django 4.1.2 on 2022-11-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_ourservice_delete_ourservic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Areaimage')),
                ('Title', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=10)),
                ('Group', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=10)),
                ('Desc', models.CharField(max_length=500)),
            ],
        ),
    ]
