# Generated by Django 4.1.2 on 2022-11-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='ourArea',
        ),
    ]
