# Generated by Django 4.1.2 on 2022-11-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0020_rename_area_ourarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='ourarea',
            name='Category',
            field=models.CharField(max_length=50),
        ),
    ]
